greeting:
  template: "Hello, %s!!!"
  defaultName: "World"
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dw_people?useUnicode=true&characterEncoding=utf8&autoReconnect=true"
    username: studio
    password: welcome
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    org.springframework.web: DEBUG