greeting:
  template: "Hello, %s!!!"
  defaultName: "World"
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dw_people?useUnicode=true&characterEncoding=utf8&autoReconnect=true"
    username: studio
    password: welcome1
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    #cache-names: c1,c2
    redis:
      time-to-live: 1800s
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: welcome1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 10000ms
        min-idle: 0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  elasticsearch:
    rest:
      uri:
        "127.0.0.1:9200"
es:
  host: "127.0.0.1"
  port: "9200"

logging:
  level:
    org.springframework.web: DEBUG
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
